### ISSUE TITLE
OS X下爆session的错误

### ISSUE THREAD

**Issue by Tu-tu-tu** [lijiejie/BBScan#11]
![](http://i4.buimg.com/4851/86f800fe6cb359ce.png)

**Comment by lijiejie** [comment]
先试试去掉--network 24，是正常的吗

**Comment by Tu-tu-tu** [comment]
去掉--network 24 是没有问题的。![](http://i1.piimg.com/4851/43babbaaf483efa5.png)

**Comment by lijiejie** [comment]
已fix，请git pull抓取最新的代码试试
