### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by webtest444** [lijiejie/BBScan#12]
win10和Debian 3.16.36-1上用，跑到线程僵死半个小时以上没反应，线程消耗cpu持续为0

**Comment by webtest444** [comment]
ip也就461个

**Comment by webtest444** [comment]
回退版本到e77f76a67bf77ff2dc617b9c8b844d00ffeea223还能用

**Comment by lijiejie** [comment]
谢谢反馈，已经在处理了，暂时定位到是requests的问题

**Comment by lijiejie** [comment]
请git pull 获取最新的代码
