### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lianfeng30** [lijiejie/BBScan#14]
python2 BBScan.py
Traceback (most recent call last):
  File "BBScan.py", line 30, in <module>
    from lib.connectionPool import HTTPConnPool, HTTPSConnPool
  File "/Users/www/BBScan-1.2.3/lib/connectionPool.py", line 5, in <module>
    from urllib3.packages.six.moves.queue import Empty
ImportError: No module named queue
www:BBScan-1.2.3 www$ pip install queuelib
Requirement already satisfied: queuelib in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

。。。

**Comment by lijiejie** [comment]
set PYTHONPATH=/Library/Python/2.7/site-packages (OSX 10.10) 

试试，参考链接   https://github.com/docker/compose/issues/2108
