### ISSUE TITLE
不知道是否BBscan是不是某些requirement存在问题

### ISSUE THREAD

**Issue by d4wner** [lijiejie/BBScan#16]
我这边直接python2.x执行提示缺少组件，比如urllib3。
直接去pip装的话，是找不到的，换了国内源也这样。
'''
Downloading/unpacking urllib3/dnspython
  Cannot fetch index base URL http://pypi.xxx.com/simple
'''
然后python3运行的话，会发现语法不对，显然不是python3。
不知道jiejie童鞋知道是怎么回事么？

**Comment by lijiejie** [comment]
可使用 python2.7 再试试

**Comment by d4wner** [comment]
鄙人用的python 2.73，刚又试了下，仍旧报错：
```
Downloading/unpacking urllib3 (from -r requirements.txt (line 3))
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement urllib3 (from -r requirements.txt (line 3))
No distributions at all found for urllib3 (from -r requirements.txt (line 3)
```
我这边是可以访问http://pypi.python.org/simple/的，网是通的，想了半天没想明白咋回事。

**Comment by Tren** [comment]
![di89q u9gei 2o agrl_1zi](https://user-images.githubusercontent.com/20461924/33479976-1a5e6c0e-d6ca-11e7-83f6-ead78d637527.png)
我也遇到了这个问题.. 不知道有什么办法可以解决

**Comment by lewisec** [comment]
@Tren 同样的问题，请问您解决了吗？

**Comment by Bosco-Lam** [comment]
@Tren  我也遇到了这个问题，你是咋解决的呢？

**Comment by Bosco-Lam** [comment]
@lewisec  我知道了，你去到urllib3的目录下看有没有six.py这个文件，没有的话，删除urllib3这个文件夹，然后重新pip install urllib3
