### ISSUE TITLE
小白求助 脚本运行的问题

### ISSUE THREAD

**Issue by graySava** [lijiejie/BBScan#18]
师傅推荐的BBScan 马上动手下载起来玩起来..
但是在windows下和linux下运行都出现了问题
requirements 都已经通过pip安装 
但是还是出错了 

![qq 20180330013812](https://user-images.githubusercontent.com/19970001/38104592-2e2868e4-33bc-11e8-89ab-2a6c7fa83c66.png)
![qq 20180330014025](https://user-images.githubusercontent.com/19970001/38104586-2aafc054-33bc-11e8-95f4-ffa881d7cdd9.png)

**Comment by zjxzjx** [comment]
我也是这个问题，no module named six.moves.queue
网上查了下，好像是没安装theano的原因
也没安装成功，到最后显示out of memory，很尴尬，期待作者解答

**Comment by ice-doom** [comment]
kali的python是2.7.14+，我用python2.7.5或者python2.7.13版本的没有问题

**Comment by lazybootsafe** [comment]
pip install requests -U 如果安装不了 翻墙试试

**Comment by 9ak47er** [comment]
@jinlanlou Kali下的python-six有问题  

apt-get remove python-six

pip uninstall six

pip install six

pip install urllib3

应该就好了

**Comment by lijiejie** [comment]
谢谢各位， 请大家参考 @9ak47er  的方法
