### ISSUE TITLE
没有二级域名扫描，感觉很难受

### ISSUE THREAD

**Issue by PHPPlay** [lijiejie/BBScan#2]
还要自己收集二级域名，会不会很麻烦？

**Comment by lijiejie** [comment]
https://github.com/lijiejie/subDomainsBrute    扫描之后是可以直接导入的

**Comment by dongchi** [comment]
使用https://github.com/ring04h/wydomain  扫描后的域名可以直接导入

**Comment by gitfuzzing** [comment]
扫完是带后面带Ip的，怎么导入？

**Comment by imfht** [comment]
使用 [https://raw.githubusercontent.com/fiht/educn-sqlScan/master/source/get_subDomain.py](https://raw.githubusercontent.com/fiht/educn-sqlScan/master/source/get_subDomain.py) 扫描后的域名是可以直接导入的

**Comment by mark0smith** [comment]
你可以试试下面的代码，需要在根目录下建立一个domains文件夹
从wydomain获取结果，导入到BBScan里扫描
``` bash
#!/bin/sh
export wydomainDir='/root/wydomain/'
export BBScanDir='/root/BBScan/'
cd $wydomainDir
pwd
python wydomain.py -d $1 -o $1
cat $1 | awk 'BEGIN{FS="\""} $0 ~ /\"/ {print $2}'|uniq |sort > ~/domains/$1

cat ~/domains/$1
cd $BBScanDir
pwd
python BBScan.py -f ~/domains/$1 
```
