### ISSUE TITLE
 --browser参数报错问题

### ISSUE THREAD

**Issue by c0ny1** [lijiejie/BBScan#20]
看了项目的说明文档中有示例可以使用--browser参数，于是
命令：BBScan.py --host www.xxx.com --browser
提示：BBScan: error: unrecognized arguments: --browser
这提示说明项目无法识别该参数，想问一下browser参数是否支持，作用何在。

**Comment by lijiejie** [comment]
已经没有这个参数了。 可以参考一下最新的说明
