### ISSUE TITLE
kali最新版本下运行出错  No module named six.moves.queue

### ISSUE THREAD

**Issue by sysalong** [lijiejie/BBScan#23]
s
root@kali:/usr/local/xxxx/BBScan-master# python BBScan.py --help
Traceback (most recent call last):
  File "BBScan.py", line 30, in <module>
    from lib.connectionPool import HTTPConnPool, HTTPSConnPool
  File "/usr/local/xxxx/BBScan-master/lib/connectionPool.py", line 5, in <module>
    from urllib3.packages.six.moves.queue import Empty
ImportError: No module named six.moves.queue

我安装最新版本的six也不可以。

现在我的six如下:
>>> six
<module 'six' from '/usr/lib/python2.7/dist-packages/six.pyc'>

**Comment by lhtest429** [comment]
+1

**Comment by popmedd** [comment]
改成import urllib3 就不会报错了

**Comment by sysalong** [comment]
把最后一行改成 from Queue import Empty  就解决了。

**Comment by lhtest429** [comment]
我把pip更新了 也好了

**Comment by lhtest429** [comment]
感谢大神们

**Comment by GlobeMasterX** [comment]
pip install awscli --upgrade --ignore-installed six
