### ISSUE TITLE
敏感信息文件扫描时，出现404和200两种状态

### ISSUE THREAD

**Issue by popmedd** [lijiejie/BBScan#24]
127.0.0.1 - - [20/Nov/2018 17:57:12] "GET http://127.0.0.1:8000//www.log HTTP/1.1" 404 -
127.0.0.1 - - [20/Nov/2018 17:57:12] code 404, message File not found
![image](https://user-images.githubusercontent.com/26320024/48821980-56169d00-ed96-11e8-9ce3-9ee506ae438e.png)
实际上去浏览器上访问返回状态 200
![image](https://user-images.githubusercontent.com/26320024/48765965-53606d00-ecee-11e8-84cd-3c7047919d0e.png)
127.0.0.1 - - [20/Nov/2018 17:58:25] "GET /www.log HTTP/1.1" 200 -
在代码中去除后http://127.0.0.1:8000/，返回状态为200了，但是扫描完后显示
No vulnerabilities found on sites in hosts
![image](https://user-images.githubusercontent.com/26320024/48821654-274bf700-ed95-11e8-8032-980e91d86786.png)

**Comment by lijiejie** [comment]
试试现在的版本，还有这个问题吗？   可能是拼接URL的时候多了 /
