### ISSUE TITLE
大家好，请问bbscan可以支持https的扫描？

### ISSUE THREAD

**Issue by Gu1st** [lijiejie/BBScan#26]
扫描https的站点都是直接404了

**Comment by 1in9e** [comment]
需要将传入的domain改为 domain:443应该就能支持了吧

**Comment by Gu1st** [comment]
> 需要将传入的domain改为 domain:443应该就能支持了吧

我刚认真学习看了下参数， 引入的domain 用https开头的就好了， 是我太笨，哈哈 ，谢谢你.

**Comment by lijiejie** [comment]
好的，请传入 https://your.site.com
