### ISSUE TITLE
some thread error

### ISSUE THREAD

**Issue by Jimmy12580** [lijiejie/BBScan#30]
最新的python+最新的BBScan 1.4 报错了，报错如下：

objc[21336]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[21336]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by lijiejie** [comment]
请试试新的版本。  另外，目前开发环境仍然是 python2.7
