### ISSUE TITLE
Avoid potential dependency conflicts between BBScan and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [lijiejie/BBScan#31]
Hi, as shown in the following full dependency graph of  **_BBScan_**, **_BBScan_** requires _**urllib3**_ (the latest version), while the installed version of **_requests_**(2.22.0) requires _**urllib3>=1.21.1,<1.26**_.

According to Pip's “first found wins” installation strategy, _**urllib3 1.25.3**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.3**_ just satisfies the later dependency constraint (_**urllib3>=1.21.1,<1.26**_), it will lead to a build failure once developers release a newer version of **_urllib3_**.

### Dependency tree--------
```
BBScan(version range:)
| +-beautifulsoup4(version range:>=4.3.2)
| +-py2-ipaddress(version range:>=3.4.1)
| +-pymongo(version range:)
| +-requests(version range:)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-urllib3(version range:)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Fix your direct dependencies to be **_urllib3>=1.21.1,<1.26_** and **_requests==2.22.0_**, to remove this conflict. 
        I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency urllib3, and use the library urllib3 transitively introduced by requests.

Personally, I prefer solution 2.
What's your opinion?
@lijiejie May I pull a request to solve this issue?

**Comment by lijiejie** [comment]
Thanks for your dependencies check,  please make a pull request.

**Comment by im23pds** [comment]
@NeolithEra hi

Hello, I still encounter some problems, how do I solve them?

Thank you。

Installing collected packages: urllib3
  Found existing installation: urllib3 1.25.8
    Uninstalling urllib3-1.25.8:
      Successfully uninstalled urllib3-1.25.8
Successfully installed urllib3-1.22
git:(master) 
~/BBScan-1.2.3 (0) git:(master) 
> python2 BBScan.py -f targets.txt                        
Traceback (most recent call last):
  File "BBScan.py", line 29, in <module>
    from lib.connectionPool import HTTPConnPool, HTTPSConnPool
  File "/Users/BBScan-1.2.3/lib/connectionPool.py", line 1, in <module>
    import urllib3
ImportError: No module named urllib3
