### ISSUE TITLE
特殊情况下扫描失败的问题

### ISSUE THREAD

**Issue by qiji2015** [lijiejie/BBScan#33]
使用bbscan的时候发现一个问题，当扫描的时候host参数没有指定协议的时候，被扫描的网站如果配置了http强制301跳转https就无法扫描。
我看了一下代码，发现代码会默认使用http连接，conn_pool = HTTPConnPool，所以导致扫描请求发不出去。
现在很多网站切换https都会采用这种301的方式，建议可以对你的项目进行一定更新
以下是我的尝试方法
bbscan.py行136增加如下代码
#start
status, headers, html_doc = self.http_request("/")
location = headers.get('Location', '')
if status == 301 and location:
        loc_schema, loc_host, loc_path = parse_url(location)
        self.base_url = location
        if loc_schema == 'https':
                self.conn_pool = HTTPSConnPool(self.host, port=443, maxsize=self.args.t * 2, headers=HEADERS)
        if loc_schema == 'http':
                self.conn_pool = HTTPConnPool(self.host, port=443, maxsize=self.args.t * 2, headers=HEADERS)
        print_msg('Location scan web: %s' % location)
#end

**Comment by lijiejie** [comment]
感谢qiji兄， 代码已经修改了。 添加了跳转的检查

https://github.com/lijiejie/BBScan/commit/af852f3d0f2d98a0c5fde5823a15ec8d29c520ea
