### ISSUE TITLE
Invalid domain问题

### ISSUE THREAD

**Issue by lavon321** [lijiejie/BBScan#55]
url文件过大时会出现Invalid domain，无法解析域名
<img width="716" alt="image" src="https://user-images.githubusercontent.com/50451123/229331475-09e7c5f2-6b7e-4ba9-b4a2-31eb3cc3fb10.png">

**Comment by lijiejie** [comment]
Hi , 新的版本已经解决。 减少了DNS查询的并发，解决家庭网络下DNS查询不稳定的问题
